### PR TITLE
Add player & board classes. Add basic user interaction.

### PR DESCRIPTION
**Pull request by memelopez**
Added player and board classes and most of the user interface when taking turns to play. Still needs some validation on the position

### CODE REVIEW

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
# Status: Change Requested

Good job @memelopez for nailing the user interface it's looking good and its almost done only small changes you need to make so that your project can be approved

## To highlights image

- The game asks players for their names.
- The game tells which player turn it is
- The game asks the player to select from available moves.
- The game informs the player if the selected move is invalid
- The game displays the board after the player move

## To improve image

- Player names are not validated because your game now can accept empty name
- The game is supposed to inform the  player if the selected move is a draw move

draw

- The game is supposed to inform the player if the selected move is a winning move

win

### Kindly fix that and submit another CRR


Regards,

Lydia Ingabire

Slack: Delice Lydia
[Linkedin](https://www.linkedin.com/in/delice-lydia/)
[Twitter](https://twitter.com/IngabireLydia3)

**Comment by memelopez** [comment]
Hi Lydia!
Thank you for your quick response. I'm just a bit confused. Do I need to
validate if a player wins? I thought that was part of the game logic,
milestone 3. I think I submitted for milestone 2, user interface.

Elmer

**Comment by DeliceLydia** [comment]
Hey @memelopez yeah the requirements said that you need to implement a winning move you don't need to go far in the game on this milestone but show at least one winning move its required

**Review by BigWizzo — APPROVED** [review]
# Approved :heavy_check_mark:  

### Hello  @memelopez :wave:

## :clap: :clap: :clap: Congratulations , your project is approved

- [ ] [OPTIONAL]  I noticed you had a hard time understanding what is required of you in this Milestone. The milestone required you to mock the basic flow of the game. This means implementing a user interface that displays prompts for users (print/puts) and collects user input (gets.chomp). In the end, you needed to print/puts a mock statement telling the user whether they have won, lost or the game has been a draw without necessarily making the game work. The actual logic is meant for the next milestone.

Will Nyamunokora

- Github: [@bigwizzo](https://github.com/bigwizzo)
- Linkedin: [willnyamunokora](https://www.linkedin.com/in/willnyamunokora/)
- Slack: [@will](https://microverse-students.slack.com/team/U0162QV2TLK)

**Pull request merged**
